name: Release
on:
  push:
    branches:
      - master
      - beta
jobs:
  release:
    name: Package and Release
    runs-on: ubuntu-latest
    permissions:
       contents: write # to be able to publish a GitHub release
       issues: write # to be able to comment on released issues
       pull-requests: write # to be able to comment on released pull request
       id-token: write # to enable use of OIDC for npm provenance
    outputs:
      new_tag_version: ${{ steps.tag_version.outputs.new_tag_version }}
      release_notes: ${{ steps.tag_version.outputs.release_notes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: semantic-release-dry-run
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export NEXT_TAG_VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
          echo "new_tag_version=${NEXT_TAG_VERSION}" >> "$GITHUB_OUTPUT"
          echo $NEXT_TAG_VERSION 

          echo "release_notes=${npx semantic-release --dry-run | awk '/Release note for version/'}" >> "$GITHUB_OUTPUT"         
  print-sematic-variables:
      name: Print variables
      runs-on: ubuntu-latest
      needs: release
      steps:
        - name: Print Release number
          run: |
            echo ${{ needs.release.outputs.new_tag_version }}
            echo ${{ needs.release.outputs.release_notes }}
